// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwzbqczdxpapnosdpmbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3emJxY3pkeHBhcG5vc2RwbWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTk4MjgsImV4cCI6MjA2MDAzNTgyOH0._7iWTKTrHG7YMnVmckTLrCf2f1wAfpHDJATOojre9HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);